#3 Handles Jobs Without Requirement of WaitGroup
burntcarrot/octopool pull request #4
Opened 2021-10-03 20:51 UTC by eemike07

Fixes #3 

My original idea to follow the [example](https://github.com/gammazero/workerpool#example) provided didn't quite work out how I intended....for some reason the execution dropped off by the time `pool.Wait()` was called.
So I thought of a more simpler approach....move the `WaitGroups` into the Worker Pool.

Would like some feedback.
If this is an acceptable approach, I can update the documentation.

2021-10-04 03:37 UTC, burntcarrot commented on octopus.go
> +}
These lines are not covered by any tests, could you please add a small test covering this too?

2021-10-04 03:41 UTC, burntcarrot requested changes
Great work! Could you please provide a screenshot of `octopool` running any sample jobs on your PC, using the newer approach made in this PR?

2021-10-04 14:28 UTC, eemike07 commented on octopus.go
> +}
Will do!  Sorry for late response - ^^ I most likely live in a different time zone.  I'll knock this out after work today.

2021-10-04 14:29 UTC, eemike07 commented
> Great work! Could you please provide a screenshot of `octopool` running any sample jobs on your PC, using the newer approach made in this PR?

I'll provide screenshots later today.  Would running the benchmarks suffice?

2021-10-04 20:25 UTC, eemike07 commented on octopus.go
> +}
Provided unit tests

2021-10-05 03:42 UTC, burntcarrot commented on octopus.go
> +}
Thanks! Looks better now :)

2021-10-05 03:44 UTC, burntcarrot approved these changes
Looks good to me!

2021-10-05 03:49 UTC, burntcarrot commented
@eemike07 Thank you for your contribution! It has been great working with you throughout this PR! Merging.

Welcome to Hacktoberfest! Have fun! 😄

2021-10-05 03:50 UTC, merged

2021-10-05 03:54 UTC, eemike07 commented
@burntcarrot Thank you for giving me this opportunity to contribute!!! It was fun!!! :)

2021-10-05 03:58 UTC, burntcarrot commented
@eemike07 Your contribution is highlighted in the [v0.1.2](https://github.com/burntcarrot/octopool/releases/tag/v0.1.2) release notes, thank you for making a significant contribution! 🎉🥳